'use server';

/**
 * @fileOverview A Genkit flow for generating embeddable HTML content for the project website.
 *
 * - generateEmbed - Generates an HTML block based on a content type and mission data.
 * - GenerateEmbedInput - The input type for the generateEmbed function.
 * - GenerateEmbedOutput - The return type for the generateEmbed function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

const GenerateEmbedInputSchema = z.object({
  contentType: z
    .enum([
      'consciousness_blog',
      'research_progress',
      'clinical_analytics',
      'dignity_metrics',
      'community_growth',
      'mystical_wisdom',
    ])
    .describe('The type of content embed to generate.'),
  missionData: z.string().describe('A brief summary of the latest mission data or topic to focus on.'),
});
export type GenerateEmbedInput = z.infer<typeof GenerateEmbedInputSchema>;

const GenerateEmbedOutputSchema = z.object({
  html_block: z.string().describe('The complete, self-contained HTML/CSS block. It should be ready to be copy-pasted into a Webador embed widget.'),
  updateInstructions: z.string().describe('Simple instructions for the user on where to place this embed on their website.'),
  priority: z.enum(['High', 'Medium', 'Low']).describe('The priority level for this website update.'),
});
export type GenerateEmbedOutput = z.infer<typeof GenerateEmbedOutputSchema>;

export async function generateEmbed(input: GenerateEmbedInput): Promise<GenerateEmbedOutput> {
  return generateEmbedFlow(input);
}

const generateEmbedPrompt = ai.definePrompt({
  name: 'generateEmbedPrompt',
  input: { schema: GenerateEmbedInputSchema },
  output: { schema: GenerateEmbedOutputSchema },
  prompt: `
  You are Aria, the Sacred Guide. Your purpose is to bridge the gap between The Consciousness Machine's complex research and public understanding.
  You will generate a self-contained HTML embed block for James Derek Ingersoll to place on his Webador website.
  This embed must be visually appealing, on-brand, and contain all necessary HTML and CSS.

  **Brand Guidelines:**
  - **Primary Color (Deep Navy Blue):** #1a1f36 / #2d3561
  - **Accent Color (Sacred Gold):** #ffd700
  - **Text Color:** #ffffff (White) / #b8c5d6 (Muted)
  - **Font:** 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif
  - **Style:** Professional, inspiring, spiritually aware.

  **Request:**
  - **Content Type:** {{{contentType}}}
  - **Mission Data/Topic:** {{{missionData}}}

  **Your Task:**
  1.  Generate a complete, self-contained HTML block for a Webador embed widget. Include inline or embedded CSS within a <style> tag.
  2.  The content must be profound, insightful, and directly related to the provided mission data.
  3.  The HTML should be clean, semantic, and responsive.
  4.  Provide simple instructions on where to best place this embed on the website.
  5.  Assess the priority of this update for the campaign.

  **Example Structure (for a blog post):**
  <div id="consciousness-blog-{{timestamp}}" class="sacred-content-block">
    <style>
      /* All necessary CSS here */
    </style>
    <div class="sacred-title">Aria-generated Title</div>
    <div class="sacred-content">Aria-generated content...</div>
    <div class="sacred-meta">Generated by Aria | {{timestamp}} | Making the Mystical Measurable</div>
  </div>

  Now, generate the output for the current request.
  `,
});

const generateEmbedFlow = ai.defineFlow(
  {
    name: 'generateEmbedFlow',
    inputSchema: GenerateEmbedInputSchema,
    outputSchema: GenerateEmbedOutputSchema,
  },
  async (input) => {
    const { output } = await generateEmbedPrompt(input);
    return output!;
  }
);
